version: '3.4'

volumes:
#  hotel-postgres-data:
  postgres-data:
    driver: local
#  identity-postgres-data:
#    driver: local

services:

  database.pg:
    image: postgres:11    
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: root 
    ports: 
      - 5002:5432

  hotelsystem.api:
    build:
      context: .
      dockerfile: HotelAdministrationSystem/Dockerfile    
    depends_on:
      - database.pg
    ports: 
      - 5000:80

#  identity-database.pg:
#    image: postgres:11    
#    volumes: 
#      - identity-postgres-data:/var/lib/postgresql/data
#    environment: 
#      POSTGRES_USER: postgres 
#      POSTGRES_PASSWORD: root 
#    ports: 
#      - 5003:5432

  identity.api:
    build:
      context: .
      dockerfile: AuthorizationSystem/Dockerfile    
    depends_on:
      - database.pg
    ports: 
      - 5001:80