// <auto-generated />
using System;
using HotelAdministrationSystem.Domain.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HotelAdministrationSystem.Migrations
{
    [DbContext(typeof(HotelSystemDBContext))]
    [Migration("20190705200905_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HotelAdministrationSystem.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("ClientGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DepartureDate");

                    b.Property<DateTime>("EntryDate");

                    b.Property<string>("Name");

                    b.Property<string>("Patronymic");

                    b.Property<string>("Surname");

                    b.HasKey("ClientGuid");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("HotelAdministrationSystem.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<int>("RoomType");

                    b.HasKey("RoomGuid");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelAdministrationSystem.Domain.Entities.RoomState", b =>
                {
                    b.Property<Guid>("RoomStateGuid");

                    b.Property<Guid>("ClientGuid");

                    b.Property<Guid>("RoomGuid");

                    b.HasKey("RoomStateGuid");

                    b.HasIndex("ClientGuid");

                    b.HasIndex("RoomGuid");

                    b.ToTable("RoomStates");
                });

            modelBuilder.Entity("HotelAdministrationSystem.Domain.Entities.RoomState", b =>
                {
                    b.HasOne("HotelAdministrationSystem.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HotelAdministrationSystem.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
